CREATE TABLE NOBRANDMEMBER(
	ID VARCHAR2(50) NOT NULL,
	PW VARCHAR2(1000) NOT NULL,
	NAME VARCHAR2(20) NOT NULL,
	AUTH CHAR(1) CONSTRAINT MEMBER_CK CHECK (AUTH IN ('A','U')) NOT NULL, -- A또는 U 반드시 입력
	DELFLAG CHAR(1) NOT NULL,
	REGDATE DATE NOT NULL,
	CONSTRAINT NOBRANDMEMBER_PK PRIMARY KEY (ID)
);


CREATE TABLE NOBRANDBOARD(
	SEQ NUMBER NOT NULL,
	ID VARCHAR2(50) NOT NULL,
	TITLE VARCHAR2(100) NOT NULL,
	CONTENT VARCHAR2(1000) NOT NULL,
	REFER NUMBER NOT NULL,
	STEP NUMBER NOT NULL,
	"DEPTH" NUMBER NOT NULL,
	READCOUNT NUMBER NOT NULL,
	DELFLAG CHAR(1) NOT NULL,
	REGDATE DATE NOT NULL,
	CONSTRAINT NOBRANDBOARD_PK PRIMARY KEY (SEQ),
	CONSTRAINT NOBRANDBOARD_FK FOREIGN KEY(ID) REFERENCES NOBRANDMEMBER(ID)
);

CREATE SEQUENCE NOBRANDBOARD_SEQ START WITH 1 INCREMENT BY 1;